### ISSUE TITLE
Refactor configuration

### ISSUE THREAD

**Issue by safl** [refenv/cijoe#60]
Currently all configuration-file items have a top-level identifier e.g. ``fio``, ``qemu``, etc. This clashes a bit with the configuration-items for **cijoe** itself, e.g. the configuration of cijoe-transports has top-level item ``transport``. For example, for the configuration-content:

```toml
[transport.ssh]
username = "root"
password = "root"
hostname = "localhost"
port = 4200
```

This could be under top-level item ``cijoe``. e.g.:

```toml
[cijoe.transport.ssh]
username = "root"
password = "root"
hostname = "localhost"
port = 4200
```

This will align nicely with the recent addition of specifying ``env`` and ``shell`` for ``cijoe.run``, which looks like:

```toml
[cijoe.run]
shell = "csh"
env = {FOO = "bar", JAZZ= "tazz"}
```
