### ISSUE TITLE
get() / put() from workflow

### ISSUE THREAD

**Issue by safl** [refenv/cijoe#76]
The workflow-files currently support invoking scripts and commands.
They are lacking the data-transfer primitives ``cijoe.get()`` / ``cijoe.put()``, this should be enabled by adding to core-scripts "get.py" and "put.py" that simply invoke cijoe, and thus making it usable via e.g.:

```yaml
- name: download
  uses: core.get
  with:
    src: path_on_initiator
    dst: path_on_target
```
